<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeuBarbeiro.Domain\MeuBarbeiro.Domain.csproj" />
    <ProjectReference Include="..\MeuBarbeiro.Contracts\MeuBarbeiro.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
